#!/bin/sh
# Autoware 1.5.0 local setup script (POSIX sh, does not source ROS base)
# Usage: . /opt/autoware/1.5.0/local_setup.sh

_AUTOWARE_HOME="/opt/autoware/1.5.0"

# Set up Autoware workspace paths
AMENT_PREFIX_PATH="$_AUTOWARE_HOME${AMENT_PREFIX_PATH:+:$AMENT_PREFIX_PATH}"
CMAKE_PREFIX_PATH="$_AUTOWARE_HOME${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH}"
COLCON_PREFIX_PATH="$_AUTOWARE_HOME${COLCON_PREFIX_PATH:+:$COLCON_PREFIX_PATH}"
PATH="$_AUTOWARE_HOME/bin${PATH:+:$PATH}"
LD_LIBRARY_PATH="$_AUTOWARE_HOME/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
PYTHONPATH="$_AUTOWARE_HOME/lib/python3.10/site-packages${PYTHONPATH:+:$PYTHONPATH}"
export AMENT_PREFIX_PATH CMAKE_PREFIX_PATH COLCON_PREFIX_PATH PATH LD_LIBRARY_PATH PYTHONPATH

unset _AUTOWARE_HOME
